analytics: {}
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.331081
  lightness: 1
  rhythmicContrast: 0.508445
  saturation: 1
cta: {}
layout_spectrum: 1
name: desirables
opengraph: {}
purpose: {}
typography_spectrum: 0
