analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00cd8a'
    - '#1154a5'
    - '#747675'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.508445
  saturation: 0.25
cta: {}
layout_spectrum: 0
name: desirables
opengraph: {}
purpose:
  - {}
typography_spectrum: 0
